export const matrixPageStyles = {
  page: {
    minHeight: "100vh",
    background: "#060b14",
    color: "#e2e8f0",
    fontFamily: "'JetBrains Mono', 'Fira Code', monospace",
    padding: "40px 24px",
    boxSizing: "border-box",
  },
  header: {
    textAlign: "center",
    marginBottom: 24,
  },
  assignmentBanner: {
    maxWidth: 720,
    margin: "0 auto 28px",
    padding: "16px 20px",
    borderRadius: 12,
    background:
      "linear-gradient(135deg, rgba(5,150,105,0.12), rgba(29,78,216,0.08))",
    border: "1px solid rgba(52,211,153,0.25)",
    textAlign: "left",
  },
  assignmentTitle: {
    fontSize: 11,
    fontWeight: 800,
    letterSpacing: "0.12em",
    textTransform: "uppercase",
    color: "#34d399",
    marginBottom: 8,
  },
  assignmentText: {
    margin: 0,
    fontSize: 14,
    color: "#cbd5e1",
    lineHeight: 1.5,
  },
  assignmentMulti: {
    margin: "10px 0 0",
    fontSize: 12,
    color: "#fbbf24",
    lineHeight: 1.55,
  },
  assignmentHint: {
    margin: "10px 0 0",
    fontSize: 11,
    color: "#64748b",
    lineHeight: 1.5,
  },
  badge: {
    display: "inline-block",
    background: "#22d3ee20",
    color: "#22d3ee",
    border: "1px solid #22d3ee40",
    borderRadius: 4,
    fontSize: 11,
    letterSpacing: 4,
    padding: "3px 12px",
    marginBottom: 12,
  },
  title: {
    fontSize: "clamp(24px, 5vw, 42px)",
    fontWeight: 700,
    margin: "0 0 24px",
    letterSpacing: -1,
    background: "linear-gradient(135deg, #22d3ee, #a78bfa)",
    WebkitBackgroundClip: "text",
    WebkitTextFillColor: "transparent",
  },
  stats: {
    display: "flex",
    justifyContent: "center",
    gap: 32,
    flexWrap: "wrap",
  },
  stat: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    gap: 4,
  },
  statValue: {
    fontSize: 28,
    fontWeight: 700,
  },
  statLabel: {
    fontSize: 11,
    color: "#64748b",
    letterSpacing: 2,
    textTransform: "uppercase",
  },
  legend: {
    display: "flex",
    justifyContent: "center",
    flexWrap: "wrap",
    gap: "8px 24px",
    marginBottom: 32,
  },
  legendItem: {
    display: "flex",
    alignItems: "center",
    gap: 8,
  },
  legendDot: {
    width: 12,
    height: 12,
    borderRadius: 3,
    border: "1px solid #334155",
  },
  legendText: {
    fontSize: 12,
    color: "#94a3b8",
  },
  matrixWrapper: {
    display: "flex",
    justifyContent: "center",
    marginBottom: 40,
  },
  matrixScroll: {
    overflowX: "auto",
    borderRadius: 12,
    border: "1px solid #1e3a5f",
    boxShadow: "0 0 40px #22d3ee10",
  },
  table: {
    borderCollapse: "separate",
    borderSpacing: 3,
    padding: 8,
    background: "#07111e",
  },
  cornerCell: {
    padding: "8px 12px",
    fontSize: 9,
    color: "#334155",
    fontWeight: 400,
    letterSpacing: 0.5,
    textAlign: "center",
    minWidth: 100,
  },
  headerCell: {
    padding: "8px 0",
    textAlign: "center",
    fontSize: 13,
    fontWeight: 700,
    color: "#22d3ee",
    minWidth: 52,
    letterSpacing: 1,
  },
  rowHeaderCell: {
    padding: "0 14px 0 8px",
    fontSize: 13,
    fontWeight: 700,
    color: "#22d3ee",
    textAlign: "right",
    letterSpacing: 1,
  },
  cell: {
    width: 52,
    height: 52,
    textAlign: "center",
    verticalAlign: "middle",
    fontSize: 14,
    fontWeight: 700,
    borderRadius: 6,
    transition: "all 0.2s",
    cursor: "default",
    userSelect: "none",
  },
  null: {
    fontSize: 16,
    opacity: 0.25,
  },
  edgeList: {
    maxWidth: 700,
    margin: "0 auto",
  },
  sectionTitle: {
    fontSize: 13,
    fontWeight: 600,
    color: "#475569",
    letterSpacing: 3,
    textTransform: "uppercase",
    marginBottom: 16,
  },
  edgeGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fill, minmax(160px, 1fr))",
    gap: 8,
  },
  edgeCard: {
    background: "#0f1f33",
    border: "1px solid #1e3a5f",
    borderRadius: 8,
    padding: "10px 14px",
    display: "flex",
    flexDirection: "column",
    gap: 4,
  },
  edgeCardAssigned: {
    border: "1px solid #10b981",
    boxShadow: "0 0 16px rgba(16,185,129,0.2)",
    background: "rgba(5,150,105,0.08)",
  },
  edgeRoute: {
    fontSize: 14,
    fontWeight: 700,
    color: "#cbd5e1",
  },
  arrow: {
    color: "#22d3ee",
  },
  edgeWeight: {
    fontSize: 11,
    color: "#a78bfa",
  },
  loopBadge: {
    fontSize: 10,
    background: "#6366f120",
    color: "#a5b4fc",
    border: "1px solid #6366f140",
    borderRadius: 4,
    padding: "1px 6px",
    alignSelf: "flex-start",
    letterSpacing: 1,
  },
};
